name: oneshot
services:
  blog:
    build: ./docker/blog
	dockerfile: Dockerfile
    ports:
      - 55
	environment:
	  - HOME=/home/user
    deploy:
      mode: replicated
      replicas: 2

  ng:
    build: ./docker/ngrinder
	dockerfile: Dockerfile
	ports:
	  - "80:80"
	environment:
	  - HOME=/home/user
	
  db:
    build: ./docker/db
	dockerfile: Dockerfile
	environment:
	  - HOME=/home/usr
	
