name: oneshot
services:
  blog:
    build: 
	  context: ./docker/blog
	  dockerfile: Dockerfile
    ports:
      - "8501:8501" # Streamlit port
	  - "3000:3000" # Grafana port
	environment:
	  - HOME=/home/user

  ng:
    build: ./docker/ngrinder
	dockerfile: Dockerfile
	ports:
	  - "80:80"
	environment:
	  - HOME=/home/user
	
  db:
    build: ./docker/db
	dockerfile: Dockerfile
	environment:
	  - HOME=/home/usr
	
