name: oneshot
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: mariadb_container
    env_file:
      - .env  # 환경 변수 파일 경로
      - ./docker/db/config/.my.cnf # exporter 환경변수 파일경로
    ports:
      - "3551:3306"  #/prometheus --config.file# 포트 매핑
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/config:/etc/mysql/conf.d
    # command: ./download/mysqld_exporter-0.15.1.linux-amd64/mysqld_exporter --config.my-cnf=/download/setting/.my.cnf

  blog:
    build: 
      context: ./docker/blog
      dockerfile: Dockerfile

  parking:
    build: 
      context: ./docker/httpd
      dockerfile: Dockerfile
    ports:
      - 80
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: '0.05'
          memory: 50M
        limits:
          cpus: '0.01'
          memory: 50M
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80

  dashboard:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000" # Grafana port
    container_name: grafana_container
    volumes:
      - ./grafana-storage:/var/lib/grafana
    user: "0:0"  # root 권한으로 실행
    restart: unless-stopped
        
  ng:
    build:
      context: ./docker/ngrinder
      dockerfile: Dockerfile
    ports:
      - "60:60"
      - "443:443"
      - "9090:9090" # Prometheus 포트
    container_name: nginx_container
    volumes:
      - ./docker/ngrinder/default.conf:/etc/nginx/conf.d/default.conf  # nginx 설정 파일 저장 경로 (필요시 변경)
      - ./docker/ngrinder/prometheus.yml:/download/prometheus-2.53.3.linux-amd64/prometheus.yml
      - ./ngrinder_data:/ngrinder-controller-3.5.9-p1  # ngrinder 데이터 저장 경로 (필요시 변경)
    environment:
      - HOME=/home/user
    # command: /download/prometheus-2.53.3.linux-amd64/prometheus --config.file=/download/prometheus-2.53.3.linux-amd64/prometheus.yml
    depends_on:
      - parking
   
