name: oneshot
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: mariadb_container
    env_file:
      - .env  # 환경 변수 파일 경로
      - ./docker/db/.my.cnf # exporter 환경변수 파일경로
    ports:
      - "3551:3551"  # 포트 매핑
    volumes:
      - ./docker/db:/download/mysqld_exporter-0.15.1.linux-amd64/setting/
    command: > 
      ./mysqld_exporter-0.15.1.linux-amd64/mysqld_exporter --config.my-cnf=/download/mysqld_exporter-0.15.1.linux-amd64/setting/.my.cnf
  blog:
    build: 
      context: ./docker/blog
      dockerfile: Dockerfile
    ports:
      - "8501:8501" # Streamlit port
    container_name: streamlit_container
    environment:
      - HOME=/home/user
    depends_on:
      - db

  dashboard:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000" # Grafana port
    container_name: grafana_container
    volumes:
      - ./grafana-storage:/var/lib/grafana
    user: "0:0"  # root 권한으로 실행
    restart: unless-stopped
        
  ng:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx:1.25
    ports:
      - "60:60"
      - "443:443"
      - "9090:9090" # Prometheus 포트
    container_name: nginx_container
    volumes:
      - ./docker/ngrinder/default.conf:/etc/nginx/conf.d/default.conf  # nginx 설정 파일 저장 경로 (필요시 변경)
      - /prometheus-2.53.3.linux-amd64  # Prometheus 데이터 저장 경로 (필요시 변경) 
      - ./ngrinder_data:/ngrinder-controller-3.5.9-p1  # ngrinder 데이터 저장 경로 (필요시 변경)
    environment:
      - HOME=/home/user
    depends_on:
      - blog
